[package]
name = "dino-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.9"
proc-macro2 = "1.0.84"
quote = "1.0.36"
syn = { version = "2.0.66", features = ["extra-traits"] }
